name: Android Build

on:
  push:
    branches:
      - main
      - next
  workflow_dispatch: # This enables manual triggering

jobs:
  build-android:
    name: Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@master
        with:
          channel: stable

      - name: Build Flutter app for Android
        run: flutter build apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0 # Update this with your desired version number
          release_name: Release v1.0.0 # Update this with your desired release name
          draft: false
          prerelease: false

      - name: Upload APK
        id: upload_apk
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk # Update the path to your APK

      - name: Add APK link to Release Description
        run: echo "Download the APK [here](https://github.com/${{ github.repository }}/releases/download/${{ steps.create_release.outputs.id }}/app-release.apk)" >> $GITHUB_EVENT_PATH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
